### ISSUE TITLE
2024-06-21 19:13:44 | ERROR    | 190 - n4 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')

### ISSUE THREAD

**Issue by mrdarkerr** [Freddywhest/MemeFiBot#10]
```
2024-06-21 19:13:44 | ERROR    | 190 - n4 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
2024-06-21 19:13:44 | ERROR    | 190 - n1 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
2024-06-21 19:13:44 | ERROR    | 311 - n3 | ❗️Unknown error when Tapping: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
2024-06-21 19:13:44 | ERROR    | 190 - end | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')url=URL('https://api-gw-tg.memefi.club/graphql')
```

**This error returns when I use multi-account**

**Comment by Freddywhest** [comment]
Close the it and start again

**Comment by bond2bill** [comment]
> ```
> 
> 2024-06-21 19:13:44 | ERROR    | 190 - n4 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> 
> 2024-06-21 19:13:44 | ERROR    | 190 - n1 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> 
> 2024-06-21 19:13:44 | ERROR    | 311 - n3 | ❗️Unknown error when Tapping: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> 
> 2024-06-21 19:13:44 | ERROR    | 190 - end | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')url=URL('https://api-gw-tg.memefi.club/graphql')
> 
> ```
> 
> 
> 
> **This error returns when I use multi-account**

Multi account, should use multi proxy. Memefi using cloudflared for api gateway, 429 is respone from cloudflare.

**Comment by mrdarkerr** [comment]
> > ```
> > 
> > 2024-06-21 19:13:44 | ERROR    | 190 - n4 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> > 
> > 2024-06-21 19:13:44 | ERROR    | 190 - n1 | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> > 
> > 2024-06-21 19:13:44 | ERROR    | 311 - n3 | ❗️Unknown error when Tapping: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')
> > 
> > 2024-06-21 19:13:44 | ERROR    | 190 - end | ❗️Unknown error while getting Bot Config: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')url=URL('https://api-gw-tg.memefi.club/graphql')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **This error returns when I use multi-account**
> 
> Multi account, should use multi proxy. Memefi using cloudflared for api gateway, 429 is respone from cloudflare.

Can you guide me how to use a proxy for each account? 
What is the type of proxy?
