### ISSUE TITLE
First time run still have error <Unknown error while getting ... [403]>

### ISSUE THREAD

**Issue by thanhnguyen92** [Freddywhest/MemeFiBot#16]
I tried with a completely new account, and this is the first MemeFi bot that runs with the same error as other repository bots.
For old accounts, I tried waiting 12-24 hours like this issue #3 says, but the problem still persists.

**Environment:**
I only use 1 account on server to run in this context.
Other game bots run normally.

**Error:**
![image](https://github.com/Freddywhest/MemeFiBot/assets/25925555/4bc41d98-f0e3-4287-beba-d3dba14540b6)

**Comment by shelllshock** [comment]
same!

**Comment by Freddywhest** [comment]
Restart the bot multiple times

**Comment by boika** [comment]
> Try it without proxies or restart it multiple times

Didn't help me

**Comment by Freddywhest** [comment]
I don't have that issue so I don't know how to solve it
Try https://github.com/Freddywhest/MemeFiBot/issues/7

**Comment by boika** [comment]
Downgrade python from 3.11.9 to 3.10.11 helped.

**Comment by ipinternet** [comment]
FROM python:3.10.11-alpine3.18

It is my Dockerfile config. Still Same problem.

**Comment by Freddywhest** [comment]
> FROM python:3.10.11-alpine3.18
> 
> It is my Dockerfile config. Still Same problem.

Use it without docker

**Comment by prognt** [comment]
`FROM python:3.10.11-alpine3.18`
error 403
`FROM python:3.11.9-alpine3.20`
all good

**Comment by thanhnguyen92** [comment]
Install version Python [3.10.0](https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe) and issue is fixed.
