### ISSUE TITLE
❗ ️Unknown e rror: 'NoneType' object is not subscriptable | 

### ISSUE THREAD

**Issue by ipinternet** [Freddywhest/MemeFiBot#17]
![Screenshot_20240708-190250_Termius](https://github.com/Freddywhest/MemeFiBot/assets/78790000/5d1da3dc-9092-4bd6-a1fc-9f423ae5cc73)

❗ ️Unknown e
rror while getting Access Token: 403, message='Forbidden', url=UR
L('https://api-gw-tg.memefi.club/graphql')

**Comment by Freddywhest** [comment]
Check this https://github.com/Freddywhest/MemeFiBot/issues/16#issuecomment-2212581096

**Comment by ipinternet** [comment]
FROM python:3.10.11-alpine3.18

It is my Dockerfile config. Still Same problem.

Please tell me now.

**Comment by ipinternet** [comment]
I have already many bot running. How can I run it with specific python version?
