### ISSUE TITLE
Error: 'NoneType' object is not subscriptable when call send_tap()

### ISSUE THREAD

**Issue by bond2bill** [Freddywhest/MemeFiBot#3]
Log error as:

2024-06-20 19:22:41 | ERROR    | bot.core.tapper:send_taps | ❗️Unknown error when Tapping: 'NoneType' object is not subscriptable
2024-06-20 19:22:41 | ERROR    | bot.core.tapper:send_taps | ❗️Unknown error when Tapping: 'NoneType' object is not subscriptable
2024-06-20 19:22:41 | ERROR    | bot.core.tapper:send_taps | ❗️Unknown error when Tapping: 'NoneType' object is not subscriptable

Please help me fix.

Thank you.

**Comment by Freddywhest** [comment]
Launch memefi on your phone and send some taps if it works and try again

**Comment by GeRRyOD** [comment]
The same problem, but i think it is server side...

**Comment by Freddywhest** [comment]
Restart the bot

**Comment by GeRRyOD** [comment]
> Restart the bot

❗️Unknown error when Tapping: 'NoneType' object is nt subscriptable

**Comment by Freddywhest** [comment]
I tried running 3 different bot with 3 different account and it's working 100%.

**Try the following and give me feedback:**

1. Try upgrading damage level or energy cap level from the mobile app and see if it's the level increases
2. Try applying turbo from the mobile app if it works

**Comment by GeRRyOD** [comment]
> I tried running 3 different bot with 3 different account and it's working 100%.
> 
> **Try the following and give me feedback:**
> 
> 1. Try upgrading damage level or energy cap level from the mobile app and see if it's the level increases
> 2. Try applying turbo from the mobile app if it works

Now it's work. The problem was on server side. But now all looking good :)
