### ISSUE TITLE
Big Problem 

### ISSUE THREAD

**Issue by Pawansingh333** [Freddywhest/MemeFiBot#4]
I ran the bot, and it worked, but when I reached level 11 in the Memefi game, it got stuck. The enemies aren't showing up, and I'm not gaining coins by tapping. Please tell me the solution.

**Comment by Freddywhest** [comment]
Yeah, After level 11, there ain't any boss to kill so the game has end

**Comment by Pawansingh333** [comment]
ok thanks for reply
