### ISSUE TITLE
Please Help 

### ISSUE THREAD

**Issue by Pawansingh333** [Freddywhest/MemeFiBot#8]
Hay Devloper you saying After level 11, there ain't any boss to kill so the game has end, But Game saying continue playing please watch this Image and reply 
![photo_2024-06-21_12-06-01](https://github.com/Freddywhest/MemeFiBot/assets/167502767/829390a2-d42b-44b3-9d6c-06b79351d04e)

**Comment by Freddywhest** [comment]
MemeFi end with boss 11 that's why there ain't any image in boss 12 box

**Comment by Pawansingh333** [comment]
ok thanks devloper
